# This file contains hiring statics for a firm such as experience of candidate, his written test score and personal interview score. Based on these 3 factors, HR will decide the salary

### 2 yr experience, 9 test score, 6 interview score
### 12 yr experience, 10 test score, 10 interview score

In [4]:
import numpy as pd
import pandas as pd

In [5]:
pip install word2number

Note: you may need to restart the kernel to use updated packages.


In [8]:
# we need to convert the string into number
from word2number import w2n

In [9]:
df = pd.read_csv('D:\\_practice_data\\hiring_data_set.csv')
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [10]:
# filling the null values through 0
df.experience = df.experience.fillna('zero')
df.experience

0      zero
1      zero
2      five
3       two
4     seven
5     three
6       ten
7    eleven
Name: experience, dtype: object

In [11]:
# There is no null values in "experience features"  
df.experience = df.experience.fillna('zero')
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [12]:
# filling the "experience" features through integer
df.experience = df.experience.apply(w2n.word_to_num)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [13]:
# checking the null values
df['test_score(out of 10)'].isnull().sum()

1

In [14]:
# finding the median value
df['test_score(out of 10)'].mean()

7.857142857142857

In [15]:
import math
median_test_score = math.floor(df['test_score(out of 10)'].mean())
median_test_score

7

In [16]:
# clean the data set
df['test_score(out of 10)'] = df['test_score(out of 10)'].fillna(median_test_score)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    7.0                           7      72000
7          11                    7.0                           8      80000

In [18]:
# importing the model
from sklearn import linear_model

In [19]:
reg = linear_model.LinearRegression()
reg.fit(df[['experience','test_score(out of 10)','interview_score(out of 10)']],df['salary($)'])

LinearRegression()

# 2 yr experience, 9 test score, 6 interview score

In [20]:
# predicting the 2yrs experience, 9 test scored, 6 interview score
reg.predict([[2,9,6]])

C:\Users\Kavya\anaconda3\lib\site-packages\sklearn\base.py:441: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53713.86677124])

In [21]:
# checking coefficient
reg.coef_

array([2922.26901502, 2221.30909959, 2147.48256637])

In [22]:
# checking the intercept
reg.intercept_

14992.65144669314

In [23]:
# checking through statistically
2922.26901502*2+2221.30909959*9+2147.48256637*6+14992.65144669314

53713.86677126314

# 12 yr experience, 10 test score, 10 interview score

In [24]:
# predicting the 2yrs experience, 9 test scored, 6 interview score
reg.predict([[12,10,10]])

C:\Users\Kavya\anaconda3\lib\site-packages\sklearn\base.py:441: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([93747.79628651])

In [25]:
# checking coefficient
reg.coef_

array([2922.26901502, 2221.30909959, 2147.48256637])

In [26]:
# checking the intercept
reg.intercept_

14992.65144669314

In [27]:
# checking through statistically
2922.26901502*12+2221.30909959*10+2147.48256637*10+14992.65144669314

93747.79628653315